# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - practiceDocker2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://practicedocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c329c39087554c618e0b4e2dd0827eb4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63092d5bfb0b42fb864c9da1e838ac8c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'practiceDocker2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e13c87f6b9c3415b94bfa687aac2e6fb }}
        images: 'practicedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c329c39087554c618e0b4e2dd0827eb4 }}/practice:${{ github.sha }}'
